bump version to 2.0.14
aws-cloudformation/cloudformation-cli-java-plugin pull request #411
Opened 2023-01-04 19:52 UTC by AkifRafique

*Issue #, if available:*
bump version
*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-04 19:57 UTC, bcorman3 approved these changes

2023-01-27 00:00 UTC, himanshs23 approved these changes

2023-01-27 00:02 UTC, ammokhov requested changes
dont need to bump runtime version?

2023-01-27 21:53 UTC, himanshs23 approved these changes

2023-01-27 22:00 UTC, ammokhov approved these changes

2023-02-14 22:18 UTC, merged